---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rpi
    image: python:3-alpine
    networks:
      - name: molecule-test
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8    
provisioner:
  name: ansible
  options:
    skip-tags: molecule-converge-notest
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge_catch.yml
    cleanup: ../resources/cleanup.yml
    verify: ../resources/verify.yml
  inventory:
    host_vars:
      rpi:
        # Some action are taken about this variable in prepare.yml depending
        # the molecule execution context (natively or from docker container)
        noobs_repo_server: 
          - "http://noobs_repo:8080/os_list_double.json"
        requested_os_name: "Test OS 2"

        # Specific test variable used by the prepare playbook
        test_noobs_partition: "noobs_partition/"

        # Specific test variable to check result
        test_failure_from_converge: False
        waited_failed_task_name: "Failed if too much Package available"
        waited_failed_result_msg: "More than 1 package is available for the release 'latest' of os 'Test OS 2'."
        waited_os_dir: "test_os_1"
        waited_os_date: "2019-01-01"

verifier:
  name: testinfra
  options:
    v: true
  directory: ../resources/tests_err/
  additional_files_or_dirs: 
    - ../tests/test_os.py

scenario:
  test_sequence:
    #- dependency
    - lint
    - cleanup
    - destroy
    #- syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    - cleanup
    - destroy