---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rpi
    image: python:3-alpine
    networks:
      - name: molecule-test
    network_mode: molecule-test
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8    
provisioner:
  name: ansible
  options:
    skip-tags: molecule-converge-notest
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge_catch.yml
    cleanup: ../resources/cleanup.yml
  inventory:
    host_vars:
      rpi:
        # Some action are taken about this variable in prepare.yml depending
        # the molecule execution context (natively or from docker container)
        noobs_repo_server: "http://noobs_repo:8080/os_list.json"
        requested_os_name: "Test os wrong marketing tar"

        # Specific test variable used by the prepare playbook
        test_noobs_partition: "noobs_partition/"

        # Specific test variable to check result
        test_failure_from_converge: False
        waited_failed_task_name: "Repostiroy Marketing tarball Error"
        waited_failed_result_msg: "Archive http://noobs_repo:8080/test_os_5/marketing.tar is not valid"
        waited_os_dir: "test_os_1"
        waited_os_date: "2019-01-01"

verifier:
  name: testinfra
  options:
    vvv: true
  directory: ../resources/tests_err/
  additional_files_or_dirs: 
    - ../tests/test_os.py

scenario:
  test_sequence:
    #- dependency
    - lint
    - cleanup
    - destroy
    #- syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    - cleanup
    - destroy
