---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rpi
    image: python:3-alpine
    networks:
      - name: molecule-test
    network-mode: molecule-test
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  options:
    skip-tags: molecule-converge-notest
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    cleanup: ../resources/cleanup.yml
  inventory:
    host_vars:
      rpi:
        # Some action are taken about this variable in prepare.yml depending
        # the molecule execution context (natively or from docker container)
        noobs_repo_server: "http://noobs_repo:8080/os_list.json"
        
        # Specific test variable used by the prepare playbook
        test_noobs_partition: "noobs_partition_mutiple_os/"

        # Specific test variable used by the tests
        waited_os_dir: "raspios_lite_armhf"
        waited_os_date: "2020-08-20"
verifier:
  name: testinfra
  options:
    v: true
  directory: ../resources/tests/
