---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rpi
    image: fletort/sshd-python3-alpine
    override_command: false
    volumes:
    # if molecule inside container use HOST_PWD as base directory
    # if molecule is executed natively, use MOLECULE_PROJECT_DIRECTORY as base directory
      - ${HOST_PWD:-$MOLECULE_PROJECT_DIRECTORY}/molecule/resources/files/entrypoint.d/:/etc/entrypoint.d/:ro
      - ${HOST_PWD:-$MOLECULE_PROJECT_DIRECTORY}/molecule/resources/files/fake_boot_time/:/fake_boot_time/:ro
      - ${HOST_PWD:-$MOLECULE_PROJECT_DIRECTORY}/molecule/resources/files/keys/:/etc/ssh/keys/:rw
    networks:
      - name: molecule-test
    env:
      SSH_ENABLE_ROOT_PASSWORD_AUTH: "true"
    ports:
      - "2222:22"
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8    
provisioner:
  name: ansible
  options:
    skip-tags: molecule-converge-notest
    #tags: molecule-converge-stub-reboot
  playbooks:
    prepare: ../resources/prepare.yml
    converge: converge_ssh.yml
    cleanup: ../resources/cleanup.yml
  inventory:
    host_vars:
      rpi:
        # Specific test: force custom boot_time_command for reboot module over container
        molecule_boot_time_command: "cat /fake_boot_time/boot_id"

        # Some action are taken about this variable in prepare.yml depending
        # the molecule execution context (natively or from docker container)
        noobs_repo_server: "http://noobs_repo:8080/os_list.json"
        
        # Specific test variable used by the prepare playbook
        test_noobs_partition: "noobs_partition_mutiple_os/"

        # Specific test variable used by the tests
        waited_os_dir: "raspios_lite_armhf"
        waited_os_date: "2020-08-20"
verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    #- idempotence
    #- side_effect
    - verify
    - cleanup
    - destroy
